version: "3.8"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"

  backend:
    build: .
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    ports:
      - "3300:3000"
    depends_on:
      - mongo

